---
 - hosts: all
   become: true
   vars:
     vim_config_path: /home/alex/git/vim-config

   tasks:

    - name: Install packages
      pacman:
        pkg:
          - neovim
          - git
          - go
          - curl
          - python3
          - python-jedi
          - fzf
          - rust
          - code
          - python-pynvim
          - docker
          - docker-compose
        state: latest
        update_cache: true

    - name: get vim config
      git:
        repo: https://github.com/gurkslask/vim-config.git
        dest: "{{ vim_config_path }}"

    - name: move folder
      copy:
        remote_src: True
        src: "{{ vim_config_path + '/nvim' }}"
        dest: /home/alex/.config/


