---
 - hosts: all
   become: true
   vars:
     vim_config_path: /home/dittnamn/git/vim-config

   tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install packages
      apt:
        pkg:
          - neovim
          - git
          - golang
          - curl
          - python3
          - python3-jedi
          - python3-pip
          - fzf
        state: latest
        update_cache: true

    - name: get vim config
      git:
        repo: https://github.com/gurkslask/vim-config.git
        dest: "{{ vim_config_path }}"

    - name: move folder
      copy:
        remote_src: True
        src: "{{ vim_config_path + '/nvim' }}"
        dest: /home/dittnamn/.config/


